name: push

on: [push, pull_request]

jobs:
    lint:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python_version: [3.9]
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@master

            - name: Setup python ${{ matrix.python_version }}
              uses: actions/setup-python@master
              with:
                  python-version: ${{ matrix.python_version }}

            - name: pre-commit checks
              run: |
                  python -m pip install pre-commit
                  pre-commit run --all-files --show-diff-on-failure --color=always
